fin=open('Books.csv','w')
fin.write(',Book,Author,Year released')
fin.write('\n')
fin.write('0, To kill a MOckingbird, Harper Lee, 1960')
fin.write('\n')
fin.write('1, A brief history of time, Stephen Hawking, 1988')
fin.write('\n')
fin.write('2,The great gatsby, F.Scott Fitzgerald, 1922')
fin.write('\n')
fin.write('3,the man who mistook his wife for a hat,Oliver Sacks,1985')
fin.write('\n')
fin.write('4, Pride and prejudice,Jane Austen,1813')
fin.close()